### ISSUE TITLE
How to re-run test script of nmtscore

### ISSUE THREAD

**Issue by longmai-pinbus** [ZurichNLP/nmtscore#6]
Hi @jvamvas

I'm doing a research on cross-lingual plagiarism identification and found your tool is so good. I tried to run your test script (with steps that you pointed out in README.md).
![image](https://user-images.githubusercontent.com/121840543/220666193-f2e42ae0-19a7-487e-b677-8e576b31306d.png)

When run the script with "prism", I ran into this error
![image](https://user-images.githubusercontent.com/121840543/220666797-cbf11fb4-6d1e-4327-bf08-cfd195addd89.png)

Then, I modified the model from prism to small100 and ran the script again, but it took me more than 12 hours waiting and nothing happen.

Could you tell me the exactly way to re-run the script and which format of dataset should I choose if I want to run test on cross-lingual plagiarism identification between English and Vietnamese?

Thanks,

**Comment by jvamvas** [comment]
Hi @longmai-pinbus, the script is for reproducing Table 2 in the paper. Yes, it takes some time and memory.

To evaluate cross-lingual plagiarism identification between English and Vietnamese I would recommend to create your own evaluation script.

Maybe along the lines of:
```python
from nmtscore import NMTScorer

scorer = NMTScorer()
num_correct = 0
for sentence_en, sentence_vi, gold_label in my_dataset:
    similarity_score = scorer.score(sentence_en, sentence_vi)
    num_correct += (similarity_score > my_threshold) == gold_label
accuracy = num_correct / len(my_dataset)
```

**Comment by jvamvas** [comment]
Closing this, feel free to reopen
